config/routes.rb
Rails.application.routes.draw do
  resources :gps

end

app/models/gp.rb
class Gp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gps_controller.rb
class GpsController < ApplicationController
  before_action :set_gp, only: [:show, :edit, :update, :destroy]

  # GET /gps
  # GET /gps.json
  def index
    @gps = Gp.all
    require 'socket'               # Get sockets from stdlib

server = TCPServer.open(2000)  # Socket to listen on port 2000
loop {                         # Servers run forever
  client = server.accept       # Wait for a client to connect
  @respons = client.gets(10)
  client.close                 # Disconnect from the client
}
  end

  # GET /gps/1
  # GET /gps/1.json
  def show
  end

  # GET /gps/new
  def new
    @gp = Gp.new
  end

  # GET /gps/1/edit
  def edit
  end

  # POST /gps
  # POST /gps.json
  def create
    @gp = Gp.new(gp_params)

    respond_to do |format|
      if @gp.save
        format.html { redirect_to @gp, notice: 'Gp was successfully created.' }
        format.json { render :show, status: :created, location: @gp }
      else
        format.html { render :new }
        format.json { render json: @gp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gps/1
  # PATCH/PUT /gps/1.json
  def update
    respond_to do |format|
      if @gp.update(gp_params)
        format.html { redirect_to @gp, notice: 'Gp was successfully updated.' }
        format.json { render :show, status: :ok, location: @gp }
      else
        format.html { render :edit }
        format.json { render json: @gp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gps/1
  # DELETE /gps/1.json
  def destroy
    @gp.destroy
    respond_to do |format|
      format.html { redirect_to gps_url, notice: 'Gp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gp
      @gp = Gp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gp_params
      params.require(:gp).permit(:location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gps_helper.rb
module GpsHelper
end

app/views/gps/_form.html.erb
<%= form_for(@gp) do |f| %>
  <% if @gp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gp.errors.count, "error") %> prohibited this gp from being saved:</h2>

      <ul>
      <% @gp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gps/edit.html.erb
<h1>Editing Gp</h1>

<%= render 'form' %>

<%= link_to 'Show', @gp %> |
<%= link_to 'Back', gps_path %>

app/views/gps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gps</h1>

<table>
  <thead>
    <tr>
      <th>Location, IP= <%=  IPSocket.getaddress(Socket.gethostname) %></th>
      <th colspan="3"><% =@respons %></th>
    </tr>
  </thead>

  <tbody>
    <% @gps.each do |gp| %>
      <tr>
        <td><%= gp.location %></td>
        <td><%= link_to 'Show', gp %></td>
        <td><%= link_to 'Edit', edit_gp_path(gp) %></td>
        <td><%= link_to 'Destroy', gp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gp', new_gp_path %>

app/views/gps/new.html.erb
<h1>New Gp</h1>

<%= render 'form' %>

<%= link_to 'Back', gps_path %>

app/views/gps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @gp.location %>
</p>

<%= link_to 'Edit', edit_gp_path(@gp) %> |
<%= link_to 'Back', gps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>